---
abstract: 'SchemaEvolution - manage the evolution of a database with simple files'
author:
  - 'Oliver Charles <oliver.g.charles@googlemail.com>'
generated_by: 'Dist::Zilla version 1.093220'
license: ~
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SchemaEvolution
requires:
  Config::Tiny: 0
  DBI: 0
  File::Find::Rule: 0
  File::Slurp: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::Has::Sugar: 0
  Path::Class: 0
  Try::Tiny: 0
version: 0.01
